/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salasdecomputo.vistas;

import salasdecomputo.clases.estudiante;
import salasdecomputo.clases.profesor;

/**
 *
 * @author aser
 */
public class vistaPrograma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaPrograma.class.getName());

    /**
     * Creates new form vistaPrograma
     */
    public vistaPrograma() {
        initComponents();
    }
    public vistaPrograma(estudiante e) {
        initComponents();
        txt2.setText("Bienvenido " + e.getNombre());
    }
    
    public vistaPrograma(profesor p) {
        initComponents();
        txt3.setText("Bienvenido " + p.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        bgAdmin = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        bgEstudiante = new javax.swing.JPanel();
        txt2 = new javax.swing.JLabel();
        bgProfesor = new javax.swing.JPanel();
        txt3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1.setText("Bienvenido");

        javax.swing.GroupLayout bgAdminLayout = new javax.swing.GroupLayout(bgAdmin);
        bgAdmin.setLayout(bgAdminLayout);
        bgAdminLayout.setHorizontalGroup(
            bgAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1)
                .addContainerGap(782, Short.MAX_VALUE))
        );
        bgAdminLayout.setVerticalGroup(
            bgAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", bgAdmin);

        txt2.setText("Bienvenido");

        javax.swing.GroupLayout bgEstudianteLayout = new javax.swing.GroupLayout(bgEstudiante);
        bgEstudiante.setLayout(bgEstudianteLayout);
        bgEstudianteLayout.setHorizontalGroup(
            bgEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt2)
                .addContainerGap(782, Short.MAX_VALUE))
        );
        bgEstudianteLayout.setVerticalGroup(
            bgEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt2)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estudiante", bgEstudiante);

        txt3.setText("Bienvenido");

        javax.swing.GroupLayout bgProfesorLayout = new javax.swing.GroupLayout(bgProfesor);
        bgProfesor.setLayout(bgProfesorLayout);
        bgProfesorLayout.setHorizontalGroup(
            bgProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt3)
                .addContainerGap(782, Short.MAX_VALUE))
        );
        bgProfesorLayout.setVerticalGroup(
            bgProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt3)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Profesor", bgProfesor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vistaPrograma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgAdmin;
    private javax.swing.JPanel bgEstudiante;
    private javax.swing.JPanel bgProfesor;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    // End of variables declaration//GEN-END:variables
}
