/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salasdecomputo.vistas;

import salasdecomputo.clases.estudiante;
import salasdecomputo.clases.profesor;

/**
 *
 * @author aser
 */
public class vistaPrograma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaPrograma.class.getName());

    /**
     * Creates new form vistaPrograma
     */
    public vistaPrograma() {
        initComponents();
    }
    
    public vistaPrograma(estudiante e) {
        initComponents();
        txt2.setText("Bienvenido " + e.getNombre());
    }
    
    public vistaPrograma(profesor p) {
        initComponents();
        txt3.setText("Bienvenido " + p.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        bgAdmin = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        btnAdminCerrarSesion = new javax.swing.JButton();
        bgEstudiante = new javax.swing.JPanel();
        txt2 = new javax.swing.JLabel();
        btnEstudianteCerrarSesion = new javax.swing.JButton();
        bgProfesor = new javax.swing.JPanel();
        txt3 = new javax.swing.JLabel();
        btnProfesorCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1.setText("Bienvenido Admin");

        btnAdminCerrarSesion.setText("Cerrar sesión");
        btnAdminCerrarSesion.addActionListener(this::btnAdminCerrarSesionActionPerformed);

        javax.swing.GroupLayout bgAdminLayout = new javax.swing.GroupLayout(bgAdmin);
        bgAdmin.setLayout(bgAdminLayout);
        bgAdminLayout.setHorizontalGroup(
            bgAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 628, Short.MAX_VALUE)
                .addComponent(btnAdminCerrarSesion)
                .addContainerGap())
        );
        bgAdminLayout.setVerticalGroup(
            bgAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdminCerrarSesion)
                    .addComponent(txt1))
                .addContainerGap(437, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", bgAdmin);

        txt2.setText("Bienvenido juan lopez perez andamio");

        btnEstudianteCerrarSesion.setText("Cerrar sesión");
        btnEstudianteCerrarSesion.addActionListener(this::btnEstudianteCerrarSesionActionPerformed);

        javax.swing.GroupLayout bgEstudianteLayout = new javax.swing.GroupLayout(bgEstudiante);
        bgEstudiante.setLayout(bgEstudianteLayout);
        bgEstudianteLayout.setHorizontalGroup(
            bgEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 517, Short.MAX_VALUE)
                .addComponent(btnEstudianteCerrarSesion)
                .addContainerGap())
        );
        bgEstudianteLayout.setVerticalGroup(
            bgEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstudianteCerrarSesion)
                    .addComponent(txt2))
                .addContainerGap(437, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estudiante", bgEstudiante);

        txt3.setText("Bienvenido miguel gabriel martinez gonzales");

        btnProfesorCerrarSesion.setText("Cerrar sesión");
        btnProfesorCerrarSesion.addActionListener(this::btnProfesorCerrarSesionActionPerformed);

        javax.swing.GroupLayout bgProfesorLayout = new javax.swing.GroupLayout(bgProfesor);
        bgProfesor.setLayout(bgProfesorLayout);
        bgProfesorLayout.setHorizontalGroup(
            bgProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 475, Short.MAX_VALUE)
                .addComponent(btnProfesorCerrarSesion)
                .addContainerGap())
        );
        bgProfesorLayout.setVerticalGroup(
            bgProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProfesorCerrarSesion)
                    .addComponent(txt3))
                .addContainerGap(437, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Profesor", bgProfesor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCerrarSesionActionPerformed
        // TODO add your handling code here:
        vistaLogin ventana = new vistaLogin();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdminCerrarSesionActionPerformed

    private void btnEstudianteCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteCerrarSesionActionPerformed
        // TODO add your handling code here:
        vistaLogin ventana = new vistaLogin();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstudianteCerrarSesionActionPerformed

    private void btnProfesorCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesorCerrarSesionActionPerformed
        // TODO add your handling code here:
        vistaLogin ventana = new vistaLogin();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnProfesorCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vistaPrograma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgAdmin;
    private javax.swing.JPanel bgEstudiante;
    private javax.swing.JPanel bgProfesor;
    private javax.swing.JButton btnAdminCerrarSesion;
    private javax.swing.JButton btnEstudianteCerrarSesion;
    private javax.swing.JButton btnProfesorCerrarSesion;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    // End of variables declaration//GEN-END:variables
}
