/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salasdecomputo.vistas;

import javax.swing.JOptionPane;
import salasdecomputo.clases.estudiante;
import salasdecomputo.clases.estudianteDAO;
import salasdecomputo.clases.profesor;
import salasdecomputo.clases.profesorDAO;

/**
 *
 * @author aser
 */
public class vistaLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaLogin.class.getName());

    /**
     * Creates new form vistaLogin
     */
    public vistaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        img1 = new javax.swing.JLabel();
        divInputs = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        inputUsuario = new javax.swing.JTextField();
        txt2 = new javax.swing.JLabel();
        inputContraseña = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salasdecomputo/imagenes/unicordoba_logo.png"))); // NOI18N
        img1.setAutoscrolls(true);

        divInputs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txt1.setText("Usuario:");

        txt2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txt2.setText("Contraseña:");

        btnIngresar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);

        javax.swing.GroupLayout divInputsLayout = new javax.swing.GroupLayout(divInputs);
        divInputs.setLayout(divInputsLayout);
        divInputsLayout.setHorizontalGroup(
            divInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divInputsLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnIngresar)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(divInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(divInputsLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addGroup(divInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(divInputsLayout.createSequentialGroup()
                            .addComponent(txt1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inputUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(divInputsLayout.createSequentialGroup()
                            .addComponent(txt2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inputContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        divInputsLayout.setVerticalGroup(
            divInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divInputsLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(btnIngresar)
                .addContainerGap())
            .addGroup(divInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(divInputsLayout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addGroup(divInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt1)
                        .addComponent(inputUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(divInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt2)
                        .addComponent(inputContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(67, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(divInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img1)
                .addGap(148, 148, 148))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:

        String usr = inputUsuario.getText();
        String pass = inputContraseña.getText();

        if (!(inputContraseña.getText().isEmpty()) && !(inputUsuario.getText().isEmpty())) {

            if (estudianteDAO.buscarEstudiante(usr, pass) != null) {

                estudiante e = estudianteDAO.buscarEstudiante(usr, pass);

                System.out.println("id: " + e.getId());
                System.out.println("nombre: " + e.getNombre());
                System.out.println("contraseña: " + e.getContraseña());
                System.out.println("activo: " + e.isActivo());
                System.out.println("carrera: " + e.getCarrera());

                if (e.isActivo()) {
                    vistaPrograma ventana = new vistaPrograma(e);
                    ventana.setVisible(true);
                    this.setVisible(false);
                } else if (!(e.isActivo())) {
                    JOptionPane.showMessageDialog(rootPane, "Este usuario no está activo\npidale a un administrador que lo active para poder ingresar");
                }
            } else if (profesorDAO.buscarProfesor(usr, pass) != null) {

                profesor p = profesorDAO.buscarProfesor(usr, pass);

                System.out.println("id: " + p.getId());
                System.out.println("nombre: " + p.getNombre());
                System.out.println("contraseña: " + p.getContraseña());
                System.out.println("activo: " + p.isActivo());
                System.out.println("carrera: " + p.getDepartamento());
                System.out.println("horaInicio: " + p.getHoraInicio());
                System.out.println("horaFIn: " + p.getHoraFin());

                if (p.isActivo()) {
                    vistaPrograma ventana = new vistaPrograma(p);
                    ventana.setVisible(true);
                    this.setVisible(false);
                } else if (!(p.isActivo())) {
                    JOptionPane.showMessageDialog(rootPane, "Este usuario no está activo\npidale a un administrador que lo active para poder ingresar");
                }
            } else if (usr.equals("admin") && pass.equals("123")) {
                vistaPrograma ventana = new vistaPrograma();
                ventana.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Usuario o contraseña invalidos.");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe llenar todos los campos.");
        }

        

    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vistaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPanel divInputs;
    private javax.swing.JLabel img1;
    private javax.swing.JTextField inputContraseña;
    private javax.swing.JTextField inputUsuario;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    // End of variables declaration//GEN-END:variables
}
