/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salasdecomputo.vistas;

import javax.swing.JOptionPane;
import salasdecomputo.clases.estudiante;
import salasdecomputo.clases.estudianteDAO;
import salasdecomputo.clases.profesor;

/**
 *
 * @author aser
 */
public class vistaPrograma extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaPrograma.class.getName());

    /**
     * Creates new form vistaPrograma
     */
    public vistaPrograma() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public vistaPrograma(estudiante e) {
        initComponents();
        txt2.setText("Bienvenido " + e.getNombre());
        this.setLocationRelativeTo(null);
    }

    public vistaPrograma(profesor p) {
        initComponents();
        txt3.setText("Bienvenido " + p.getNombre());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        bgAdmin = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        btnAdminCerrarSesion = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        bgAñadirEstudiante = new javax.swing.JPanel();
        contenedor1 = new javax.swing.JPanel();
        txt8 = new javax.swing.JLabel();
        inputAdminNombre = new javax.swing.JTextField();
        txt9 = new javax.swing.JLabel();
        inputAdminContraseña = new javax.swing.JTextField();
        txt10 = new javax.swing.JLabel();
        inputAdminCarrera = new javax.swing.JTextField();
        btnAdminCrearEstudiante = new javax.swing.JButton();
        bgEliminarEstudiante = new javax.swing.JPanel();
        bgAñadirProfesor = new javax.swing.JPanel();
        bgEliminarProfesor = new javax.swing.JPanel();
        bgActivarUsuario = new javax.swing.JPanel();
        bgDesactivarUsuario = new javax.swing.JPanel();
        bgEstudiante = new javax.swing.JPanel();
        txt2 = new javax.swing.JLabel();
        btnEstudianteCerrarSesion = new javax.swing.JButton();
        bgProfesor = new javax.swing.JPanel();
        txt3 = new javax.swing.JLabel();
        btnProfesorCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1.setText("Bienvenido Admin");

        btnAdminCerrarSesion.setText("Cerrar sesión");
        btnAdminCerrarSesion.addActionListener(this::btnAdminCerrarSesionActionPerformed);

        contenedor1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt8.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txt8.setText("Nombre estudiante:");

        txt9.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txt9.setText("Contraseña estudiante:");

        txt10.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txt10.setText("Carrera estudiante:");

        btnAdminCrearEstudiante.setText("Crear estudiante");
        btnAdminCrearEstudiante.addActionListener(this::btnAdminCrearEstudianteActionPerformed);

        javax.swing.GroupLayout contenedor1Layout = new javax.swing.GroupLayout(contenedor1);
        contenedor1.setLayout(contenedor1Layout);
        contenedor1Layout.setHorizontalGroup(
            contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(contenedor1Layout.createSequentialGroup()
                            .addComponent(txt8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(inputAdminNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(contenedor1Layout.createSequentialGroup()
                            .addComponent(txt9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(inputAdminContraseña))
                        .addGroup(contenedor1Layout.createSequentialGroup()
                            .addComponent(txt10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(inputAdminCarrera)))
                    .addComponent(btnAdminCrearEstudiante))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        contenedor1Layout.setVerticalGroup(
            contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt8)
                    .addComponent(inputAdminNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt9)
                    .addComponent(inputAdminContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt10)
                    .addComponent(inputAdminCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdminCrearEstudiante)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgAñadirEstudianteLayout = new javax.swing.GroupLayout(bgAñadirEstudiante);
        bgAñadirEstudiante.setLayout(bgAñadirEstudianteLayout);
        bgAñadirEstudianteLayout.setHorizontalGroup(
            bgAñadirEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAñadirEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bgAñadirEstudianteLayout.setVerticalGroup(
            bgAñadirEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAñadirEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Añadir estudiante", bgAñadirEstudiante);

        javax.swing.GroupLayout bgEliminarEstudianteLayout = new javax.swing.GroupLayout(bgEliminarEstudiante);
        bgEliminarEstudiante.setLayout(bgEliminarEstudianteLayout);
        bgEliminarEstudianteLayout.setHorizontalGroup(
            bgEliminarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        bgEliminarEstudianteLayout.setVerticalGroup(
            bgEliminarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Eliminar estudiante", bgEliminarEstudiante);

        javax.swing.GroupLayout bgAñadirProfesorLayout = new javax.swing.GroupLayout(bgAñadirProfesor);
        bgAñadirProfesor.setLayout(bgAñadirProfesorLayout);
        bgAñadirProfesorLayout.setHorizontalGroup(
            bgAñadirProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        bgAñadirProfesorLayout.setVerticalGroup(
            bgAñadirProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Añadir profesor", bgAñadirProfesor);

        javax.swing.GroupLayout bgEliminarProfesorLayout = new javax.swing.GroupLayout(bgEliminarProfesor);
        bgEliminarProfesor.setLayout(bgEliminarProfesorLayout);
        bgEliminarProfesorLayout.setHorizontalGroup(
            bgEliminarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        bgEliminarProfesorLayout.setVerticalGroup(
            bgEliminarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Eliminar profesor", bgEliminarProfesor);

        javax.swing.GroupLayout bgActivarUsuarioLayout = new javax.swing.GroupLayout(bgActivarUsuario);
        bgActivarUsuario.setLayout(bgActivarUsuarioLayout);
        bgActivarUsuarioLayout.setHorizontalGroup(
            bgActivarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        bgActivarUsuarioLayout.setVerticalGroup(
            bgActivarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Activar usuario", bgActivarUsuario);

        javax.swing.GroupLayout bgDesactivarUsuarioLayout = new javax.swing.GroupLayout(bgDesactivarUsuario);
        bgDesactivarUsuario.setLayout(bgDesactivarUsuarioLayout);
        bgDesactivarUsuarioLayout.setHorizontalGroup(
            bgDesactivarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        bgDesactivarUsuarioLayout.setVerticalGroup(
            bgDesactivarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Desactivar usuario", bgDesactivarUsuario);

        javax.swing.GroupLayout bgAdminLayout = new javax.swing.GroupLayout(bgAdmin);
        bgAdmin.setLayout(bgAdminLayout);
        bgAdminLayout.setHorizontalGroup(
            bgAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(bgAdminLayout.createSequentialGroup()
                        .addComponent(txt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdminCerrarSesion)))
                .addContainerGap())
        );
        bgAdminLayout.setVerticalGroup(
            bgAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdminCerrarSesion)
                    .addComponent(txt1))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Admin", bgAdmin);

        txt2.setText("Bienvenido juan lopez perez andamio");

        btnEstudianteCerrarSesion.setText("Cerrar sesión");
        btnEstudianteCerrarSesion.addActionListener(this::btnEstudianteCerrarSesionActionPerformed);

        javax.swing.GroupLayout bgEstudianteLayout = new javax.swing.GroupLayout(bgEstudiante);
        bgEstudiante.setLayout(bgEstudianteLayout);
        bgEstudianteLayout.setHorizontalGroup(
            bgEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(btnEstudianteCerrarSesion)
                .addContainerGap())
        );
        bgEstudianteLayout.setVerticalGroup(
            bgEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstudianteCerrarSesion)
                    .addComponent(txt2))
                .addContainerGap(437, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Estudiante", bgEstudiante);

        txt3.setText("Bienvenido miguel gabriel martinez gonzales");

        btnProfesorCerrarSesion.setText("Cerrar sesión");
        btnProfesorCerrarSesion.addActionListener(this::btnProfesorCerrarSesionActionPerformed);

        javax.swing.GroupLayout bgProfesorLayout = new javax.swing.GroupLayout(bgProfesor);
        bgProfesor.setLayout(bgProfesorLayout);
        bgProfesorLayout.setHorizontalGroup(
            bgProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(btnProfesorCerrarSesion)
                .addContainerGap())
        );
        bgProfesorLayout.setVerticalGroup(
            bgProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProfesorCerrarSesion)
                    .addComponent(txt3))
                .addContainerGap(437, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Profesor", bgProfesor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCerrarSesionActionPerformed
        // TODO add your handling code here:
        vistaLogin ventana = new vistaLogin();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdminCerrarSesionActionPerformed

    private void btnEstudianteCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteCerrarSesionActionPerformed
        // TODO add your handling code here:
        vistaLogin ventana = new vistaLogin();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEstudianteCerrarSesionActionPerformed

    private void btnProfesorCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesorCerrarSesionActionPerformed
        // TODO add your handling code here:
        vistaLogin ventana = new vistaLogin();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnProfesorCerrarSesionActionPerformed

    private void btnAdminCrearEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCrearEstudianteActionPerformed
        // TODO add your handling code here:

        String usr = inputAdminNombre.getText();
        String pass = inputAdminContraseña.getText();
        String carrera = inputAdminCarrera.getText();

        if (!(inputAdminNombre.getText().isEmpty() && inputAdminContraseña.getText().isEmpty() && inputAdminCarrera.getText().isEmpty())) {

            if (!(usr.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+"))) {
                JOptionPane.showMessageDialog(rootPane, "En nombre solo puede colocar letras");
            } else if (!(carrera.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+"))) {
                JOptionPane.showMessageDialog(rootPane, "En la carrera solo puede colocar letras");
            } else if (pass.length() < 5) {
                JOptionPane.showMessageDialog(rootPane, "La contraseña debe tener 5 o más caracteres");
            } else {

                boolean consulta = estudianteDAO.ingresarEstudiante(usr, pass, carrera);

                if (consulta) {
                    JOptionPane.showMessageDialog(rootPane, "Estudiante ingresado satisfactoriamente");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No se ha podido ingresar el estudiante");
                }

                inputAdminNombre.setText("");
                inputAdminContraseña.setText("");
                inputAdminCarrera.setText("");

            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe llenar todos los campos");
        }


    }//GEN-LAST:event_btnAdminCrearEstudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vistaPrograma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgActivarUsuario;
    private javax.swing.JPanel bgAdmin;
    private javax.swing.JPanel bgAñadirEstudiante;
    private javax.swing.JPanel bgAñadirProfesor;
    private javax.swing.JPanel bgDesactivarUsuario;
    private javax.swing.JPanel bgEliminarEstudiante;
    private javax.swing.JPanel bgEliminarProfesor;
    private javax.swing.JPanel bgEstudiante;
    private javax.swing.JPanel bgProfesor;
    private javax.swing.JButton btnAdminCerrarSesion;
    private javax.swing.JButton btnAdminCrearEstudiante;
    private javax.swing.JButton btnEstudianteCerrarSesion;
    private javax.swing.JButton btnProfesorCerrarSesion;
    private javax.swing.JPanel contenedor1;
    private javax.swing.JTextField inputAdminCarrera;
    private javax.swing.JTextField inputAdminContraseña;
    private javax.swing.JTextField inputAdminNombre;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt10;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt8;
    private javax.swing.JLabel txt9;
    // End of variables declaration//GEN-END:variables
}
